[package]
name = "lab01"
version = "0.1.0"
authors = ["Laurent Scherer <lscherer@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.2"
read_input = "0.8"
regex = "1.4.5"
rand = "0.8.3"